---
title: Project Review 
author: Hope Grismer
date: date-modified
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
---

# Overview

Title of project:Analysis of Tick-Bourne Disease Cases Reported to DPH Between 2019-2024

Name of project author(s):Hope Grismer

Name of project reviewer: Muhammad Nasir


# Instructions

Write your comments and feedback below for each section/component of the project. The goal should be to help the author improve their project. Make comments as constructive and actionable as possible. You can provide both criticism and praise.

For each component, pick one summary statement by deleting the ones that do not apply and keeping only the one that you think most closely summarizes a given component. 

Make sure your final document compiles/renders into a readable, well-formatted html document.

Delete any sections/text of this template that are not part of your final review document. (Including these instructions.)

## Background, Context and Motivation

### Feedback and Comments

The introduction part provides a clear description including background information about the diseases, which is very important for readers who have limited knowledge about Tick-borne illnesses (TBDs), tranmission of the diseases, and the revelance of the topic. 
The only thing missing from this part is citation. I think it is important to provide some sources in the background information. 

### Summary assessment (PICK ONE, DELETE THE OTHERS)

* strong contextualization and motivation


## Question description

### Feedback and Comments

Research Questions and hypotheses are discribed clearly relevan with knowldge gaps provided in the context section. 

### Summary assessment
* question/hypotheses fully clear


## Data description

### Feedback and Comments

The data source is provided. However, I did not see codebook. 

### Summary assessment
* source and overall structure of data well explained


## Data wrangling and exploratory analysis

### Feedback and Comments
The data was explored very good with notes in every steps of the process. This is super helpfull. However, there is no explanation about the plots/ figures. It would be better to provide.
I like the reasons of performing particular data analysis explained.

### Summary assessment

* some weaknesses in wrangling and exploratory component




## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments

- It is clear that the study performed three different methods: logistic regression, desicion tree and random forest. Random forest performed best in this dataset. 
- I am a little bit worry about perfoming linear model for day_to_lab ~ year. We need to make sure that all assumptions of linear regression met. The 2019 point looks faraway, it might became an ourliner and seems influence the model so much. If we pay more attention for the next years, it shows increasing trend until 2023 before dicrease to 2024. 

### Summary assessment

* strong and reasonable analysis

## Presentation

### Feedback and Comments
- The overall presentation very good, using different plots and table to visualize the result. The plot for ROC is very useful. 

- I am a bit comfused about the table in 5.1. Which analyisi the table came from? Is it linar regression? why does the table shows type of diseases? 


### Summary assessment
* results are presented ok, with room for improvement



## Discussion/Conclusions


### Feedback and Comments

The finding is well discussed. However, it will be much better if the result compared with existing/ related studies to support. Strenght and limitations are addressed well. 

### Summary assessment

* minor parts wrong, missing or unclear



## Further comments

_Add any other comments regarding the different aspects of the project here. Write anything you think can help your classmate improve their project._



# Overall project content evaluation

## Structure
Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments

The project structure is good. However, readme.md files need to be updated. Some folders/ files need to be removed.  


### Summary assessment

* mostly clear, but some confusing parts (e.g. useless files, things in the wrong folders)



## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

### Feedback and Comments

output such as figures and tables are well documented in a folder. 

### Summary assessment

* fully and well documented



## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments

- I can run most part of the code. I only got error in library (dplyr), I needed to install with defendency. 
- The manuscript cannot be render due to reference missing. 


### Summary assessment

* small parts not reproducible or required manual intervention 



## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

WRITE YOUR FEEDBACK HERE

### Summary assessment

* strong level of thorougness


## Further comments


1.	I got issue when library (dplyr) in the packages section of “processing-code-tickcases.qdm”. I need to run this code  install.packages("dplyr", dependencies = FALSE, type = "binary"). I don’t know why it happened, could be from my side. 
2.	It is better to not install/ library package in the chunk of your code, but do it in specific place, check : 
-	 processing-code-tickcases.qdm  line 251-254 , line 358-361, line 406- 410, line 488-489, line 528-530, line 568-573, line 620-626. 
3.	Issues in “statistical-analysis-gini-index.qdm”
-	Packages are install/ library in code chunk: line 10-13, 
-	Line 20, the path/ or data location is not exist. 
-	If the file is important or part of the project, we need to provide the dataset. However, if this analysis is not an important part of the project, then we can remove it. 
4.	Issue in “statistical-analysis-poverty-rate.qdm”
-	Packages are install/ library in code chunk: line 2-4 
-	This is the same with previous file, if this is not an important part of the analysis in the project, we can remove it. 
5.	Issues in “statistical-analysis.qdm”
-	Packages are install/ library in code chunk: line 118-122, line 232, line 258
-	It would be better to put description/ interpretation in each figure. 
-	In the study description, it says that the study will use data from 2019 to 2024, but in the data completeness, the figure shows the data from 2018 (see part 3. completeness)
-	For the fiu
6.	Issue in manuscript.qdm 
-	4.5.1 Most common tick-borne disease: In this section, it says five most frequent;y reposrted cases, in my understanding, the chart will only show five TBDs. 
-	Some label value in TBDs by county chart are not in appropriate places. 
-	There are three same figures in place for TBDs cases by county. I think these figures are same. 
-	Empty tables  line 646-650 
7.	Readme.md files need to be updated. 



